/**
 * sites.ts — 사이트 옵션/이름/색상 공유 상수
 */

export const SITE_OPTIONS = [
  // 핵심 사이트
  { value: 'www.dreamitbiz.com', label: 'www', color: 'yellow' },
  { value: 'hohai.dreamitbiz.com', label: 'hohai', color: 'blue' },
  { value: 'books.dreamitbiz.com', label: 'books', color: 'green' },
  { value: 'docs.dreamitbiz.com', label: 'docs', color: 'green' },
  { value: 'papers.dreamitbiz.com', label: 'papers', color: 'purple' },
  { value: 'pbi.dreamitbiz.com', label: 'pbi', color: 'yellow' },
  { value: 'aebon.dreamitbiz.com', label: 'aebon', color: 'blue' },
  // AI Hub & AI 학습 사이트 (11개)
  { value: 'ai-hub.dreamitbiz.com', label: 'ai-hub', color: 'red' },
  { value: 'chatgpt.dreamitbiz.com', label: 'chatgpt', color: 'green' },
  { value: 'gemini.dreamitbiz.com', label: 'gemini', color: 'blue' },
  { value: 'genspark.dreamitbiz.com', label: 'genspark', color: 'purple' },
  { value: 'claude.dreamitbiz.com', label: 'claude', color: 'yellow' },
  { value: 'openclaw.dreamitbiz.com', label: 'openclaw', color: 'green' },
  { value: 'ai-agents.dreamitbiz.com', label: 'ai-agents', color: 'red' },
  { value: 'ai-media.dreamitbiz.com', label: 'ai-media', color: 'purple' },
  { value: 'autowork.dreamitbiz.com', label: 'autowork', color: 'blue' },
  { value: 'fine-tuning.dreamitbiz.com', label: 'fine-tuning', color: 'green' },
  // AI/데이터
  { value: 'ai-prompt.dreamitbiz.com', label: 'ai-prompt', color: 'purple' },
  { value: 'ai-data.dreamitbiz.com', label: 'ai-data', color: 'purple' },
  // 교육 플랫폼
  { value: 'edu-hub.dreamitbiz.com', label: 'edu-hub', color: 'purple' },
  { value: 'allthat.dreamitbiz.com', label: 'allthat', color: 'green' },
  { value: 'koreatech.dreamitbiz.com', label: 'koreatech', color: 'purple' },
  { value: 'koreait.dreamitbiz.com', label: 'koreait', color: 'blue' },
  { value: 'competency.dreamitbiz.com', label: 'competency', color: 'purple' },
  { value: 'teaching.dreamitbiz.com', label: 'teaching', color: 'green' },
  // 프로그래밍 교육
  { value: 'coding.dreamitbiz.com', label: 'coding', color: 'blue' },
  { value: 'html.dreamitbiz.com', label: 'html', color: 'blue' },
  { value: 'python-study.dreamitbiz.com', label: 'python-study', color: 'blue' },
  { value: 'java-study.dreamitbiz.com', label: 'java-study', color: 'red' },
  { value: 'c-study.dreamitbiz.com', label: 'c-study', color: 'blue' },
  { value: 'linux-study.dreamitbiz.com', label: 'linux-study', color: 'yellow' },
  { value: 'software.dreamitbiz.com', label: 'software', color: 'green' },
  // IT/자격증
  { value: 'eip.dreamitbiz.com', label: 'eip', color: 'red' },
  { value: 'sqld.dreamitbiz.com', label: 'sqld', color: 'purple' },
  { value: 'ahp-basic.dreamitbiz.com', label: 'ahp-basic', color: 'red' },
  { value: 'jobpath.dreamitbiz.com', label: 'jobpath', color: 'red' },
  { value: 'planning.dreamitbiz.com', label: 'planning', color: 'green' },
  // 비즈니스/마케팅
  { value: 'marketing.dreamitbiz.com', label: 'marketing', color: 'yellow' },
  { value: 'digitalbiz.dreamitbiz.com', label: 'digitalbiz', color: 'green' },
  { value: 'self-branding.dreamitbiz.com', label: 'self-branding', color: 'yellow' },
  { value: 'uxdesign.dreamitbiz.com', label: 'uxdesign', color: 'purple' },
  { value: 'career.dreamitbiz.com', label: 'career', color: 'green' },
  // 어학
  { value: 'english.dreamitbiz.com', label: 'english', color: 'blue' },
  { value: 'japanese.dreamitbiz.com', label: 'japanese', color: 'red' },
  { value: 'korean.dreamitbiz.com', label: 'korean', color: 'green' },
  // 기타
  { value: 'reserve.dreamitbiz.com', label: 'reserve', color: 'red' },
  { value: 'algorithm.dreamitbiz.com', label: 'algorithm', color: 'blue' },
  { value: 'webstudy.dreamitbiz.com', label: 'webstudy', color: 'green' },
  { value: 'reactstudy.dreamitbiz.com', label: 'reactstudy', color: 'blue' },
  // ── 2026-06 전수 동기화 추가 (납품 프로젝트·실습·신규 사이트) ──
  { value: 'accounting.dreamitbiz.com', label: 'accounting', color: 'blue' },
  { value: 'ai-free.dreamitbiz.com', label: 'ai-free', color: 'green' },
  { value: 'ai-literacy.dreamitbiz.com', label: 'ai-literacy', color: 'purple' },
  { value: 'aice.dreamitbiz.com', label: 'aice', color: 'red' },
  { value: 'aisw.dreamitbiz.com', label: 'aisw', color: 'yellow' },
  { value: 'aws.dreamitbiz.com', label: 'aws', color: 'blue' },
  { value: 'ax-study.dreamitbiz.com', label: 'ax-study', color: 'green' },
  { value: 'ax.dreamitbiz.com', label: 'ax', color: 'purple' },
  { value: 'basic-ai.dreamitbiz.com', label: 'basic-ai', color: 'red' },
  { value: 'basic-hub.dreamitbiz.com', label: 'basic-hub', color: 'yellow' },
  { value: 'biz-hub.dreamitbiz.com', label: 'biz-hub', color: 'blue' },
  { value: 'career-hub.dreamitbiz.com', label: 'career-hub', color: 'green' },
  { value: 'cnu.dreamitbiz.com', label: 'cnu', color: 'purple' },
  { value: 'codex.dreamitbiz.com', label: 'codex', color: 'red' },
  { value: 'coding-hub.dreamitbiz.com', label: 'coding-hub', color: 'yellow' },
  { value: 'contents.dreamitbiz.com', label: 'contents', color: 'blue' },
  { value: 'copilot.dreamitbiz.com', label: 'copilot', color: 'green' },
  { value: 'cs-hub.dreamitbiz.com', label: 'cs-hub', color: 'purple' },
  { value: 'dasco.dreamitbiz.com', label: 'dasco', color: 'red' },
  { value: 'data-structure.dreamitbiz.com', label: 'data-structure', color: 'yellow' },
  { value: 'data.dreamitbiz.com', label: 'data', color: 'blue' },
  { value: 'db-study.dreamitbiz.com', label: 'db-study', color: 'green' },
  { value: 'esg.dreamitbiz.com', label: 'esg', color: 'purple' },
  { value: 'exam-hub.dreamitbiz.com', label: 'exam-hub', color: 'red' },
  { value: 'full-stack.dreamitbiz.com', label: 'full-stack', color: 'yellow' },
  { value: 'halla.dreamitbiz.com', label: 'halla', color: 'blue' },
  { value: 'harness-study.dreamitbiz.com', label: 'harness-study', color: 'green' },
  { value: 'hrm.dreamitbiz.com', label: 'hrm', color: 'purple' },
  { value: 'hwp.dreamitbiz.com', label: 'hwp', color: 'red' },
  { value: 'instructor.dreamitbiz.com', label: 'instructor', color: 'yellow' },
  { value: 'jdy.dreamitbiz.com', label: 'jdy', color: 'blue' },
  { value: 'jobexam.dreamitbiz.com', label: 'jobexam', color: 'green' },
  { value: 'kdn2026.dreamitbiz.com', label: 'kdn2026', color: 'purple' },
  { value: 'knc.dreamitbiz.com', label: 'knc', color: 'red' },
  { value: 'komipo.dreamitbiz.com', label: 'komipo', color: 'yellow' },
  { value: 'manus.dreamitbiz.com', label: 'manus', color: 'blue' },
  { value: 'notebooklm.dreamitbiz.com', label: 'notebooklm', color: 'green' },
  { value: 'pbirobot.dreamitbiz.com', label: 'pbirobot', color: 'purple' },
  { value: 'ppt-maker.dreamitbiz.com', label: 'ppt-maker', color: 'red' },
  { value: 'ppt.dreamitbiz.com', label: 'ppt', color: 'yellow' },
  { value: 'presentation.dreamitbiz.com', label: 'presentation', color: 'blue' },
  { value: 'project.dreamitbiz.com', label: 'project', color: 'green' },
  { value: 'research.dreamitbiz.com', label: 'research', color: 'purple' },
  { value: 'rest.dreamitbiz.com', label: 'rest', color: 'red' },
  { value: 'rest01.dreamitbiz.com', label: 'rest01', color: 'yellow' },
  { value: 'rest02.dreamitbiz.com', label: 'rest02', color: 'blue' },
  { value: 'rest03.dreamitbiz.com', label: 'rest03', color: 'green' },
  { value: 'rest04.dreamitbiz.com', label: 'rest04', color: 'purple' },
  { value: 'rest05.dreamitbiz.com', label: 'rest05', color: 'red' },
  { value: 'rest06.dreamitbiz.com', label: 'rest06', color: 'yellow' },
  { value: 'rest07.dreamitbiz.com', label: 'rest07', color: 'blue' },
  { value: 'safety.dreamitbiz.com', label: 'safety', color: 'green' },
  { value: 'sangmin.dreamitbiz.com', label: 'sangmin', color: 'purple' },
  { value: 'seminar.dreamitbiz.com', label: 'seminar', color: 'red' },
  { value: 'seoultech.dreamitbiz.com', label: 'seoultech', color: 'yellow' },
  { value: 'site.dreamitbiz.com', label: 'site', color: 'blue' },
  { value: 'skala.dreamitbiz.com', label: 'skala', color: 'green' },
  { value: 'snu.dreamitbiz.com', label: 'snu', color: 'purple' },
  { value: 'solar.dreamitbiz.com', label: 'solar', color: 'red' },
  { value: 'startup.dreamitbiz.com', label: 'startup', color: 'yellow' },
  { value: 'statistics.dreamitbiz.com', label: 'statistics', color: 'blue' },
  { value: 'study.dreamitbiz.com', label: 'study', color: 'green' },
  { value: 'survey.dreamitbiz.com', label: 'survey', color: 'purple' },
  { value: 'syu.dreamitbiz.com', label: 'syu', color: 'red' },
  { value: 'templete03.dreamitbiz.com', label: 'templete03', color: 'yellow' },
  { value: 'thesis-hub.dreamitbiz.com', label: 'thesis-hub', color: 'blue' },
  { value: 'university.dreamitbiz.com', label: 'university', color: 'green' },
  { value: 'vibe-coding.dreamitbiz.com', label: 'vibe-coding', color: 'purple' },
  { value: 'vibe.dreamitbiz.com', label: 'vibe', color: 'red' },
  { value: 'web.dreamitbiz.com', label: 'web', color: 'yellow' },
  { value: 'wonjunjang.dreamitbiz.com', label: 'wonjunjang', color: 'blue' },
];

const SITE_COLOR_MAP: Record<string, string> = {
  www: 'yellow', hohai: 'blue', books: 'green', docs: 'green',
  papers: 'purple', pbi: 'yellow', aebon: 'blue',
  'ai-hub': 'red', chatgpt: 'green', gemini: 'blue', genspark: 'purple',
  claude: 'yellow', openclaw: 'green', 'ai-agents': 'red',
  'ai-media': 'purple', autowork: 'blue', 'fine-tuning': 'green',
  'ai-prompt': 'purple', 'ai-data': 'purple',
  'edu-hub': 'purple', allthat: 'green', koreatech: 'purple',
  koreait: 'blue', competency: 'purple', teaching: 'green',
  coding: 'blue', html: 'blue', 'python-study': 'blue',
  'java-study': 'red', 'c-study': 'blue', 'linux-study': 'yellow',
  software: 'green', eip: 'red', sqld: 'purple', 'ahp-basic': 'red',
  jobpath: 'red', planning: 'green',
  marketing: 'yellow', digitalbiz: 'green', 'self-branding': 'yellow',
  uxdesign: 'purple', career: 'green',
  english: 'blue', japanese: 'red', korean: 'green',
  reserve: 'red', algorithm: 'blue', webstudy: 'green',
  reactstudy: 'blue',
  accounting: 'blue', 'ai-free': 'green', 'ai-literacy': 'purple', aice: 'red',
  aisw: 'yellow', aws: 'blue', 'ax-study': 'green', ax: 'purple',
  'basic-ai': 'red', 'basic-hub': 'yellow', 'biz-hub': 'blue', 'career-hub': 'green',
  cnu: 'purple', codex: 'red', 'coding-hub': 'yellow', contents: 'blue',
  copilot: 'green', 'cs-hub': 'purple', dasco: 'red', 'data-structure': 'yellow',
  data: 'blue', 'db-study': 'green', esg: 'purple', 'exam-hub': 'red',
  'full-stack': 'yellow', halla: 'blue', 'harness-study': 'green', hrm: 'purple',
  hwp: 'red', instructor: 'yellow', jdy: 'blue', jobexam: 'green',
  kdn2026: 'purple', knc: 'red', komipo: 'yellow', manus: 'blue',
  notebooklm: 'green', pbirobot: 'purple', 'ppt-maker': 'red', ppt: 'yellow',
  presentation: 'blue', project: 'green', research: 'purple', rest: 'red',
  rest01: 'yellow', rest02: 'blue', rest03: 'green', rest04: 'purple',
  rest05: 'red', rest06: 'yellow', rest07: 'blue', safety: 'green',
  sangmin: 'purple', seminar: 'red', seoultech: 'yellow', site: 'blue',
  skala: 'green', snu: 'purple', solar: 'red', startup: 'yellow',
  statistics: 'blue', study: 'green', survey: 'purple', syu: 'red',
  templete03: 'yellow', 'thesis-hub': 'blue', university: 'green', 'vibe-coding': 'purple',
  vibe: 'red', web: 'yellow', wonjunjang: 'blue',
  localhost: 'gray',
};

/** signup_domain에서 사이트 이름 추출 — 예: hohai.dreamitbiz.com → hohai */
export function getSiteName(domain: string | null | undefined): string {
  if (!domain) return '-';
  const d = domain.toLowerCase();
  if (d.endsWith('.dreamitbiz.com')) {
    const sub = d.replace('.dreamitbiz.com', '');
    return sub || 'www';
  }
  if (d === 'dreamitbiz.com' || d === 'www.dreamitbiz.com') return 'www';
  if (d.includes('localhost') || d.includes('127.0.0.1')) return 'localhost';
  return d;
}

/** 사이트별 뱃지 색상 */
export function getSiteColor(siteName: string): string {
  return SITE_COLOR_MAP[siteName] || 'gray';
}
