/**
 * siteRegistry.ts — 전체 하위 사이트 단일 소스(SSOT)
 * www 대시보드의 모든 사이트 목록·현황이 이 레지스트리에서 파생됨.
 * 새 사이트 추가 시 여기 한 곳만 수정하면 SITE_OPTIONS·사이트 현황 등에 자동 반영.
 */
export interface SiteEntry {
  name: string;
  domain: string;
  url: string;
  color: string;
  hasPayment: boolean;
  /** 결제 사이트의 Supabase 주문 테이블 (매출 집계용) */
  ordersTable?: string;
  /** getAllOrdersAll의 site 태그 키 (테이블명과 별개) */
  ordersSite?: string;
}

export const SITES: SiteEntry[] = [
  { name: 'edu-hub', domain: 'edu-hub.dreamitbiz.com', url: 'https://edu-hub.dreamitbiz.com', color: 'purple', hasPayment: true, ordersTable: 'eh_orders', ordersSite: 'edu-hub' },
  { name: 'ai-hub', domain: 'ai-hub.dreamitbiz.com', url: 'https://ai-hub.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'biz-hub', domain: 'biz-hub.dreamitbiz.com', url: 'https://biz-hub.dreamitbiz.com', color: 'blue', hasPayment: false, ordersTable: 'biz_orders', ordersSite: 'biz-hub' },
  { name: 'cs-hub', domain: 'cs-hub.dreamitbiz.com', url: 'https://cs-hub.dreamitbiz.com', color: 'purple', hasPayment: true, ordersTable: 'csh_orders', ordersSite: 'cs-hub' },
  { name: 'basic-hub', domain: 'basic-hub.dreamitbiz.com', url: 'https://basic-hub.dreamitbiz.com', color: 'yellow', hasPayment: true, ordersTable: 'bsh_orders', ordersSite: 'basic-hub' },
  { name: 'exam-hub', domain: 'exam-hub.dreamitbiz.com', url: 'https://exam-hub.dreamitbiz.com', color: 'red', hasPayment: true, ordersTable: 'exh_orders', ordersSite: 'exam-hub' },
  { name: 'career-hub', domain: 'career-hub.dreamitbiz.com', url: 'https://career-hub.dreamitbiz.com', color: 'green', hasPayment: true, ordersTable: 'crh_orders', ordersSite: 'career-hub' },
  { name: 'thesis-hub', domain: 'thesis-hub.dreamitbiz.com', url: 'https://thesis-hub.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'coding-hub', domain: 'coding-hub.dreamitbiz.com', url: 'https://coding-hub.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'coding', domain: 'coding.dreamitbiz.com', url: 'https://coding.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'c-study', domain: 'c-study.dreamitbiz.com', url: 'https://c-study.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'python-study', domain: 'python-study.dreamitbiz.com', url: 'https://python-study.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'java-study', domain: 'java-study.dreamitbiz.com', url: 'https://java-study.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'reactstudy', domain: 'reactstudy.dreamitbiz.com', url: 'https://reactstudy.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'html', domain: 'html.dreamitbiz.com', url: 'https://html.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'algorithm', domain: 'algorithm.dreamitbiz.com', url: 'https://algorithm.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'data-structure', domain: 'data-structure.dreamitbiz.com', url: 'https://data-structure.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'linux-study', domain: 'linux-study.dreamitbiz.com', url: 'https://linux-study.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'db-study', domain: 'db-study.dreamitbiz.com', url: 'https://db-study.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'software', domain: 'software.dreamitbiz.com', url: 'https://software.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'webstudy', domain: 'webstudy.dreamitbiz.com', url: 'https://webstudy.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'koreatech', domain: 'koreatech.dreamitbiz.com', url: 'https://koreatech.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'aisw', domain: 'aisw.dreamitbiz.com', url: 'https://aisw.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'ai-prompt', domain: 'ai-prompt.dreamitbiz.com', url: 'https://ai-prompt.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'ai-data', domain: 'ai-data.dreamitbiz.com', url: 'https://ai-data.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'ai-media', domain: 'ai-media.dreamitbiz.com', url: 'https://ai-media.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'claude', domain: 'claude.dreamitbiz.com', url: 'https://claude.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'chatgpt', domain: 'chatgpt.dreamitbiz.com', url: 'https://chatgpt.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'gemini', domain: 'gemini.dreamitbiz.com', url: 'https://gemini.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'genspark', domain: 'genspark.dreamitbiz.com', url: 'https://genspark.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'copilot', domain: 'copilot.dreamitbiz.com', url: 'https://copilot.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'digitalbiz', domain: 'digitalbiz.dreamitbiz.com', url: 'https://digitalbiz.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'marketing', domain: 'marketing.dreamitbiz.com', url: 'https://marketing.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'uxdesign', domain: 'uxdesign.dreamitbiz.com', url: 'https://uxdesign.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'self-branding', domain: 'self-branding.dreamitbiz.com', url: 'https://self-branding.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'english', domain: 'english.dreamitbiz.com', url: 'https://english.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'japanese', domain: 'japanese.dreamitbiz.com', url: 'https://japanese.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'korean', domain: 'korean.dreamitbiz.com', url: 'https://korean.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'eip', domain: 'eip.dreamitbiz.com', url: 'https://eip.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'sqld', domain: 'sqld.dreamitbiz.com', url: 'https://sqld.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'ai-agents', domain: 'ai-agents.dreamitbiz.com', url: 'https://ai-agents.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'autowork', domain: 'autowork.dreamitbiz.com', url: 'https://autowork.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'fine-tuning', domain: 'fine-tuning.dreamitbiz.com', url: 'https://fine-tuning.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'vibe', domain: 'vibe.dreamitbiz.com', url: 'https://vibe.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'competency', domain: 'competency.dreamitbiz.com', url: 'https://competency.dreamitbiz.com', color: 'purple', hasPayment: true },
  { name: 'career', domain: 'career.dreamitbiz.com', url: 'https://career.dreamitbiz.com', color: 'green', hasPayment: true },
  { name: 'allthat', domain: 'allthat.dreamitbiz.com', url: 'https://allthat.dreamitbiz.com', color: 'green', hasPayment: true, ordersTable: 'at_orders', ordersSite: 'allthat' },
  { name: 'papers', domain: 'papers.dreamitbiz.com', url: 'https://papers.dreamitbiz.com', color: 'purple', hasPayment: true, ordersTable: 'pp_orders', ordersSite: 'papers' },
  { name: 'ahp_basic', domain: 'ahp-basic.dreamitbiz.com', url: 'https://ahp-basic.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'teaching', domain: 'teaching.dreamitbiz.com', url: 'https://teaching.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'planning', domain: 'planning.dreamitbiz.com', url: 'https://planning.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'books', domain: 'books.dreamitbiz.com', url: 'https://books.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'docs', domain: 'docs.dreamitbiz.com', url: 'https://docs.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'reserve', domain: 'reserve.dreamitbiz.com', url: 'https://reserve.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'openclaw', domain: 'openclaw.dreamitbiz.com', url: 'https://openclaw.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'presentation', domain: 'presentation.dreamitbiz.com', url: 'https://presentation.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'aebon', domain: 'aebon.dreamitbiz.com', url: 'https://aebon.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'jdy', domain: 'jdy.dreamitbiz.com', url: 'https://jdy.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'wonjunjang', domain: 'wonjunjang.dreamitbiz.com', url: 'https://wonjunjang.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'hohai', domain: 'hohai.dreamitbiz.com', url: 'https://hohai.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'pbirobot', domain: 'pbirobot.dreamitbiz.com', url: 'https://pbirobot.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'pbi', domain: 'pbi.dreamitbiz.com', url: 'https://pbi.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'koreait', domain: 'koreait.dreamitbiz.com', url: 'https://koreait.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'jobpath', domain: 'jobpath.dreamitbiz.com', url: 'https://jobpath.dreamitbiz.com', color: 'red', hasPayment: true, ordersTable: 'forjob_orders', ordersSite: 'jobpath' },
  { name: 'jobexam', domain: 'jobexam.dreamitbiz.com', url: 'https://jobexam.dreamitbiz.com', color: 'green', hasPayment: true, ordersTable: 'jobexam_orders', ordersSite: 'jobexam' },
  { name: 'www', domain: 'www.dreamitbiz.com', url: 'https://www.dreamitbiz.com', color: 'yellow', hasPayment: true, ordersTable: 'orders', ordersSite: 'www' },
  { name: 'instructor', domain: 'instructor.dreamitbiz.com', url: 'https://instructor.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'survey', domain: 'survey.dreamitbiz.com', url: 'https://survey.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'esg', domain: 'esg.dreamitbiz.com', url: 'https://esg.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'accounting', domain: 'accounting.dreamitbiz.com', url: 'https://accounting.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'aws', domain: 'aws.dreamitbiz.com', url: 'https://aws.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'study', domain: 'study.dreamitbiz.com', url: 'https://study.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'safety', domain: 'safety.dreamitbiz.com', url: 'https://safety.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'statistics', domain: 'statistics.dreamitbiz.com', url: 'https://statistics.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'ai-free', domain: 'ai-free.dreamitbiz.com', url: 'https://ai-free.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'ai-literacy', domain: 'ai-literacy.dreamitbiz.com', url: 'https://ai-literacy.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'aice', domain: 'aice.dreamitbiz.com', url: 'https://aice.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'ax-study', domain: 'ax-study.dreamitbiz.com', url: 'https://ax-study.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'ax', domain: 'ax.dreamitbiz.com', url: 'https://ax.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'basic-ai', domain: 'basic-ai.dreamitbiz.com', url: 'https://basic-ai.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'cnu', domain: 'cnu.dreamitbiz.com', url: 'https://cnu.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'codex', domain: 'codex.dreamitbiz.com', url: 'https://codex.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'contents', domain: 'contents.dreamitbiz.com', url: 'https://contents.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'dasco', domain: 'dasco.dreamitbiz.com', url: 'https://dasco.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'data', domain: 'data.dreamitbiz.com', url: 'https://data.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'full-stack', domain: 'full-stack.dreamitbiz.com', url: 'https://full-stack.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'halla', domain: 'halla.dreamitbiz.com', url: 'https://halla.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'harness-study', domain: 'harness-study.dreamitbiz.com', url: 'https://harness-study.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'hrm', domain: 'hrm.dreamitbiz.com', url: 'https://hrm.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'hwp', domain: 'hwp.dreamitbiz.com', url: 'https://hwp.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'kdn2026', domain: 'kdn2026.dreamitbiz.com', url: 'https://kdn2026.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'knc', domain: 'knc.dreamitbiz.com', url: 'https://knc.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'komipo', domain: 'komipo.dreamitbiz.com', url: 'https://komipo.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'manus', domain: 'manus.dreamitbiz.com', url: 'https://manus.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'notebooklm', domain: 'notebooklm.dreamitbiz.com', url: 'https://notebooklm.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'ppt-maker', domain: 'ppt-maker.dreamitbiz.com', url: 'https://ppt-maker.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'ppt', domain: 'ppt.dreamitbiz.com', url: 'https://ppt.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'project', domain: 'project.dreamitbiz.com', url: 'https://project.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'research', domain: 'research.dreamitbiz.com', url: 'https://research.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'rest', domain: 'rest.dreamitbiz.com', url: 'https://rest.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'rest01', domain: 'rest01.dreamitbiz.com', url: 'https://rest01.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'rest02', domain: 'rest02.dreamitbiz.com', url: 'https://rest02.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'rest03', domain: 'rest03.dreamitbiz.com', url: 'https://rest03.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'rest04', domain: 'rest04.dreamitbiz.com', url: 'https://rest04.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'rest05', domain: 'rest05.dreamitbiz.com', url: 'https://rest05.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'rest06', domain: 'rest06.dreamitbiz.com', url: 'https://rest06.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'rest07', domain: 'rest07.dreamitbiz.com', url: 'https://rest07.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'sangmin', domain: 'sangmin.dreamitbiz.com', url: 'https://sangmin.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'seminar', domain: 'seminar.dreamitbiz.com', url: 'https://seminar.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'seoultech', domain: 'seoultech.dreamitbiz.com', url: 'https://seoultech.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'site', domain: 'site.dreamitbiz.com', url: 'https://site.dreamitbiz.com', color: 'blue', hasPayment: false },
  { name: 'skala', domain: 'skala.dreamitbiz.com', url: 'https://skala.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'snu', domain: 'snu.dreamitbiz.com', url: 'https://snu.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'solar', domain: 'solar.dreamitbiz.com', url: 'https://solar.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'startup', domain: 'startup.dreamitbiz.com', url: 'https://startup.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'syu', domain: 'syu.dreamitbiz.com', url: 'https://syu.dreamitbiz.com', color: 'red', hasPayment: false },
  { name: 'templete03', domain: 'templete03.dreamitbiz.com', url: 'https://templete03.dreamitbiz.com', color: 'yellow', hasPayment: false },
  { name: 'university', domain: 'university.dreamitbiz.com', url: 'https://university.dreamitbiz.com', color: 'green', hasPayment: false },
  { name: 'vibe-coding', domain: 'vibe-coding.dreamitbiz.com', url: 'https://vibe-coding.dreamitbiz.com', color: 'purple', hasPayment: false },
  { name: 'web', domain: 'web.dreamitbiz.com', url: 'https://web.dreamitbiz.com', color: 'yellow', hasPayment: false },
];

export const SITE_BY_NAME: Record<string, SiteEntry> = Object.fromEntries(SITES.map(s => [s.name, s]));
export const SITE_BY_DOMAIN: Record<string, SiteEntry> = Object.fromEntries(SITES.map(s => [s.domain, s]));
